POST http://localhost:5000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
            "id":5,
            "titulo":"C++",
            "lenguaje":"c",
            "vistas":568,
            "nivel":"basico"
}

###

PUT http://localhost:5000/api/cursos/programacion/5 HTTP/1.1
Content-Type: application/json

 {
            "id":4,
            "titulo":"Python intermedio",
            "lenguaje":"python",
            "vistas":1052,
            "nivel":"intermedio"
}

###
PATCH  http://localhost:5000/api/cursos/programacion/4 HTTP/1.1
Content-Type: application/json

 {
            "titulo":"C++ intermedio",
            "vistas":252
}

###
DELETE  http://localhost:5000/api/cursos/programacion/4 HTTP/1.1